cache:
  directories:
  - $HOME/.m2
language: java
jdk: oraclejdk8
email:
  - ben.alex@acegi.com.au
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ]; then echo $GPG_KEY | base64 -d | gpg --batch --fast-import -; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ]; then mvn -B -Pdeploy --settings .travis-settings.xml deploy; fi
